config/routes.rb
Rails.application.routes.draw do

  root to: 'site#index'
  get '/about' => 'static_pages#about', as: :about
  get '/contacts' => 'contacts#new', as: :contact
  resources 'contacts', only: [:new, :create]
  get '/web_resources' => 'static_pages#web_resources', as: :web_resources
  get '/faq' => 'static_pages#faq'
  get '/chart' => 'static_pages#chart'

  devise_for :users,
             singular: :user,
             controllers: { registrations: 'registrations',
                            omniauth_callbacks: 'apis' },
             path: '',
             path_names: { sign_in: 'login',
                           sign_out: 'logout',
                           sign_up: 'register',
                           edit: 'dashboard/profile/edit' }

  devise_scope :user do
    get '/apis/github/link' => 'apis#github_callback', as: :github_callback
  end
  resource :github_webhooks, only: :create,
                             defaults: { formats: :json }

  namespace :dashboard do
    get '/' => 'base#index'
    get '/webresources' => 'base#resources'
    get '/profile' => 'users#profile'
    get '/calendar' => 'events#index'
    get '/leaderboard' => 'base#leaderboard'

    resources :todos
    resources :events
    resources :assignments,
                            only: [:show, :index] do
      resources :answers, except: [:show]
    end
  end

  namespace :staff do
    get '/' => 'base#index'
    get '/base/admin'
    get '/profile' => 'members#profile'
    resources :locations
    resources :courses
    resources :members
    put '/accept_answer' => 'answers#update_answer_acceptance'
    resources :cohorts do
      get '/students/new' => 'users#new', as: :new_student
      resources :users, path: 'students'
      resources :assignments
      resources :repos
      resources :schedules
    end
  end

  resources :boards do
    resources :conversations do
      resources :comments
    end
  end
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user
  validates :item, presence: true
end

app/controllers/dashboard/answers_controller.rb
class Dashboard::AnswersController < ApplicationController
  include SetCohort
  before_action :authenticate_user!
  before_action :set_cohort, :set_assignment
  before_action :set_answer, only: [:show, :edit, :update, :destroy]
  
  # def index
  #   @answers = @assignment.answers.order(:accepted)
  # end

  def show
  end

  def edit
  end

  def update
    @answer.user = current_user
    if @answer.update(answer_params)
      redirect_to dashboard_assignment_url(@assignment),
                  notice: 'Answer was successfully updated.'
    else
      render :edit
    end
  end

  def new
    @answer = Answer.new
  end

  def create
    @answer = @assignment.answers.build(answer_params)
    @answer.user = current_user
    if @answer.save
      current_user.add_points(25, category: 'Assignments')
      redirect_to dashboard_assignment_url(@assignment),
                  notice: 'Assignment was successfully created.'
    else
      render :new
    end
  end

  def destroy
    begin
      @answer.destroy
      flash[:notice] = 'Answer deleted!'
    rescue StandardError => error
      flash[:notice] = error.message
    end
    redirect_to dashboard_assignments_url
  end

  private

  def set_answer
    @answer = @assignment.answers.find(params[:id])
  end

  def set_assignment
    @assignment = @cohort.assignments.find(params[:assignment_id])
  end

  def answer_params
    params.require(:answer).permit(:title,
                                   :body,
                                   :accepted,
                                   :assignment_id,
                                   :user_id)
  end

end

app/controllers/dashboard/assignments_controller.rb
class Dashboard::AssignmentsController < ApplicationController
  include SetCohort
  before_action :authenticate_user!
  before_action :set_cohort

  def index
    @assignments = @cohort.assignments.order(:due_date)
  end

  def show
    @assignment = @cohort.assignments.includes(:answers).includes(:pull_requests).find(params[:id])
  end

  private

  # def set_cohort
  #   @cohort = current_user.cohort
  # end

  # def set_assignment
  #   @assignment = @cohort.assignments.find(params[:id])
  # end

  def assignment_params
    params.require(:assignment).permit(:name,
                                       :description,
                                       :category,
                                       :due_date,
                                       :cohort_id)
  end
end

app/controllers/dashboard/base_controller.rb
class Dashboard::BaseController < ApplicationController
  include SetCohort
  before_action :authenticate_user!
  before_action :set_cohort
  before_action :set_user
  before_action :leaderboard

  def index
    @assignments = @cohort.assignments.all
    @todos = @user.todos.all
    @todo = @user.todos.new
    @schedules = Schedule.all
    @schedule = Schedule.new
  end

  private

  def set_user
    @user ||= current_user
  end

  def leaderboard
    @leaders = Merit::Score.top_scored(cohort: @cohort.id)
  end
end

app/controllers/dashboard/events_controller.rb
class Dashboard::EventsController < ApplicationController
  before_action :authenticate_user!
  def index
  end

  def edit
  end

  def update
  end

  def new
  end

  def create
  end

  def show
  end

  def destroy
  end
end

app/controllers/dashboard/todos_controller.rb
class Dashboard::TodosController < ApplicationController
    before_action :authenticate_user!
    before_action :set_user
    before_action :set_todo, only: :destroy

  def new
    @todo = @user.todos.new
  end

  def create
    @todo = @user.todos.new(todo_params)
    if @todo.save
      redirect_to dashboard_path, notice: 'You saved a new item'
    else
      alert_and_render('Could not save location info', :new)
    end
  end

  def destroy
    @todo.destroy
    redirect_to dashboard_path
  end

  private

 def set_todo
    @todo = @user.todos.find(params[:id])
  end

  def todo_params
    params.require(:todo).permit(:item)
  end

  def set_user
    @user ||= current_user
  end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def edit
  end

  def update
    if current_user.update_info(user_params)
      sign_in current_user, bypass: true
      redirect_to dashboard_path, notice: 'User profile updated!'
    else
      alert_and_render('Could not update your profile...', :edit)
    end
  end

  def profile
    @user = current_user
    @user.generate_github_state! unless @user.github_state == 'linked'
  end

  private

  def user_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :email,
                                 :password,
                                 :password_confirmation,
                                 :hometown,
                                 :github_username,
                                 :github_email,
                                 :github_state,
                                 :github_access_token,
                                 :provider,
                                 :uid)
  end
end

app/helpers/dashboard/answers_helper.rb
module Dashboard::AnswersHelper
end

app/helpers/dashboard/assignments_helper.rb
module Dashboard::AssignmentsHelper
end

app/helpers/dashboard/base_helper.rb
module Dashboard::BaseHelper
end

app/helpers/dashboard/events_helper.rb
module Dashboard::EventsHelper
end

app/helpers/dashboard/todos_helper.rb
module Dashboard::TodosHelper
end

app/helpers/dashboard/users_helper.rb
module Dashboard::UsersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/todos/_form.html.erb
<%= form_for [:dashboard, @users, @todo] do |f| %>
  <!-- Check if there were any errors saving location and display them if so -->


  <!-- Begin rendering the form -->
  <div class= 'form-group'>
    <%= f.label :item, 'To Do Item' %><br>
    <%= f.text_field :item, class: 'form-control' %>
  </div>

  
  <%= f.submit 'Submit', class: 'btn btn-primary' %> 
  
  <%= link_to 'Back', dashboard_path, class: 'btn btn-primary' %><br><br>
<% end %>

app/views/dashboard/todos/_todos_modal.html.erb
<div class="modal fade" id="Todos" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Add a New To Do Item</h4>
      </div>
      <div class="modal-body">
        <%= render 'dashboard/todos/form' %>
      </div>
    <!--   <div class="modal-footer">
        <button type="button" class="btn btn-primary pull-right">Save changes</button>
      </div> -->
    </div>
  </div>
</div>

app/views/dashboard/todos/edit.html.erb
<%- page_header 'Edit To Do List' %>
<%= render 'form' %>

app/views/dashboard/todos/index.html.erb
<%- page_header 'My To Do List' %>

<table class='table table-hover'>
  <thead>
    <tr>
      <th>To Do</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.item %></td>
       
        <td><%= link_to 'View', dashboard_todo_path(todo), class: 'btn btn-xs btn-default' %></td>
   
        <td><%= link_to 'Delete', dashboard_todo_path(todo), class: 'btn btn-xs btn-default', method: :delete, 
                                            data: { 
                                                  confirm: 'Are you sure you ' \
                                                           'want to delete this item?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Add a New To Do Item', new_dashboard_todo_path, class: 'btn btn-xs btn-primary' %>

app/views/dashboard/todos/new.html.erb
<%- page_header 'To Do List' %>


<%= render 'form' %>

app/views/dashboard/todos/new.js.erb
$('#modalDiv').html('<%= j render "todos_modal" %>').find('.modal').modal();