config/routes.rb
Rails.application.routes.draw do

  root to: 'site#index'
  get '/about' => 'static_pages#about', as: :about
  get '/contacts' => 'contacts#new', as: :contact
  resources 'contacts', only: [:new, :create]
  get '/web_resources' => 'static_pages#web_resources', as: :web_resources
  get '/faq' => 'static_pages#faq'
  get '/chart' => 'static_pages#chart'

  devise_for :users,
             singular: :user,
             controllers: { registrations: 'registrations',
                            omniauth_callbacks: 'apis' },
             path: '',
             path_names: { sign_in: 'login',
                           sign_out: 'logout',
                           sign_up: 'register',
                           edit: 'dashboard/profile/edit' }

  devise_scope :user do
    get '/apis/github/link' => 'apis#github_callback', as: :github_callback
  end
  resource :github_webhooks, only: :create,
                             defaults: { formats: :json }

  namespace :dashboard do
    get '/' => 'base#index'
    get '/webresources' => 'base#resources'
    get '/profile' => 'users#profile'
    get '/calendar' => 'events#index'
    get '/leaderboard' => 'base#leaderboard'

    resources :todos
    resources :events
    resources :assignments,
                            only: [:show, :index] do
      resources :answers, except: [:show]
    end
  end

  namespace :staff do
    get '/' => 'base#index'
    get '/base/admin'
    get '/profile' => 'members#profile'
    resources :locations
    resources :courses
    resources :members
    put '/accept_answer' => 'answers#update_answer_acceptance'
    resources :cohorts do
      get '/students/new' => 'users#new', as: :new_student
      resources :users, path: 'students'
      resources :assignments
      resources :repos
      resources :schedules
    end
  end

  resources :boards do
    resources :conversations do
      resources :comments
    end
  end
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :board
  belongs_to :user
  has_many :comments, :dependent => :destroy
  validates_presence_of :title
  validates_presence_of :description
  validates_length_of :title, :maximum=>50
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  before_filter :load_board
  before_action :set_conversation, only: [:show, :edit, :update, :destroy]

  def index
    @conversations = @board.conversations
  end

  def show
  end

  def new
    @conversation = Conversation.new
  end

  def edit
  end

  def create
    @conversation = @board.conversations.new(conversation_params)
    @conversation.user = current_user
    if current_user && @conversation.save
      current_user.add_points(10, category: 'Discussions')
      @conversation.update_attributes(:user_id => current_user.id)
      redirect_to board_conversation_path(@conversation.board_id, @conversation.id)
    else
      render :new
    end
  end

  def update
    @conversation = Conversation.find(params[:id])
    if @conversation.update(conversation_params)
      @conversation.update_attributes(:user_id => current_user.id)
      redirect_to board_conversations_path(@board), notice: 'Conversation was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @conversation.destroy
    @conversation.user.subtract_points(25, category: 'Discussions')
    redirect_to board_conversations_url(@board), notice:'Conversation was successfully destroyed.'
  end

  private
    def load_board
        @board = Board.find(params[:board_id])
    end

    def set_conversation
        @conversation = Conversation.find(params[:id])
    end

    def conversation_params
      params.require(:conversation).permit(:title,
                                           :description,
                                           :last_commenter_id || current_user.id,
                                           :last_comment_at || Time.now,
                                           :user_id,
                                           :board_id)
    end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation_modal.html.erb
<div class="modal fade" id="Conversations" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
 <div class="modal-dialog">
   <div class="modal-content">
     <div class="modal-header">
       <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
       <h4 class="modal-title" id="myModalLabel">Start a New Conversation</h4>
     </div>
     <div class="modal-body">
       <%= render 'new_conversation_form' %>
     </div>
   </div>
 </div>
</div>

app/views/conversations/_form.html.erb
<%= form_for([:board, @conversation]) do |f| %>
  <% if @conversation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conversation.errors.count, "error") %> prohibited this conversation from being saved:</h2>
      <ul>
      <% @conversation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
  <%= f.label :title %><br>
  <%= f.text_field :title, :class => "form-control" %>
  <br>
  <%= f.label :description %><br>
  <%= f.text_area :description, :class => "form-control", :rows => "10" %>
</div>
<br>
<div class="actions">
  <%= f.submit :class => "btn btn-primary btn-xs" %>
</div>
<br>
<% end %>

app/views/conversations/_new_conversation_form.html.erb
<%= form_for([:board, @conversation]) do |f| %>
  <% if @conversation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conversation.errors.count, "error") %> prohibited this conversation from being saved:</h2>
      <ul>
      <% @conversation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
  <%= f.label :title %><br>
  <%= f.text_field :title, :class => "form-control" %>
  <br>
  <%= f.label :description %><br>
  <%= f.text_area :description, :class => "form-control", :rows => "10" %>
</div>
<br>
<div class="actions">
  <%= f.submit :class => "btn btn-primary btn-xs" %>
</div>
<br>
<% end %>

app/views/conversations/_new_conversations_form.html.erb
<%= form_for([:board, @conversation]) do |f| %>
  <% if @conversation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conversation.errors.count, "error") %> prohibited this conversation from being saved:</h2>
      <ul>
      <% @conversation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
  <%= f.label :title %><br>
  <%= f.text_field :title, :class => "form-control" %>
  <br>
  <%= f.label :description %><br>
  <%= f.text_area :description, :class => "form-control", :rows => "10" %>
</div>
<br>
<div class="actions">
  <%= f.submit :class => "btn btn-default" %>
</div>
<% end %>

app/views/conversations/edit.html.erb
<h1>Editing conversation</h1>

<%= render 'form' %>

<%= link_to 'Show', @conversation %> |
<%= link_to 'Back', conversations_path %>

app/views/conversations/new.html.erb
<h1>New conversation</h1>

<%= render 'form' %>

app/views/conversations/new.js.erb
$('#modalDiv').html('<%= j render "conversation_modal" %>').find('.modal').modal();

app/views/conversations/show.html.erb
<% title @conversation.title  %>

<table class="table discussion">
  <tr>
    <th width="100%">Conversation Description</th>
  </tr>
  <tr class="active">
    <td>
      <p><%= @conversation.description %></p>
    </td>
  </tr>
</table>
<p><%= button_to "New Comment", new_board_conversation_comment_path(@board, @conversation), :class => "btn btn-primary btn-xs", method: 'get', remote: true %></p>
<div id="modalDiv">
</div>
<br>
<br>
<% @conversation.comments.each do |comment| %>
<div class="comment">
  <span class="left">
    <% if comment.user.github_authorized? %>
    <%= image_tag comment.user.github_profile.image, { width: 90,
                                                       height: 90 } %><br>
    <%= comment.user.github_profile.username %>
    <% else %>
      <%= comment.user.first_name %>
    <% end %><br>
    Comments: <%= comment.user.comments.count %><br>
    <% if current_user.staff? %>
    <%= link_to "Delete", board_conversation_comment_path(@conversation.board, @conversation, comment), :confirm => 'Are you sure?', :method => :delete %>
    <% end %>
  </span>
  <span class="right"><%= comment.body %></span>
</div>
<% end %>

<!-- TODO Change link so 'delete' just deletes comment not whole conversation -->
<!-- <%= link_to "Delete", @comment, :confirm => 'Are you sute?', :method => :delete %> -->