config/routes.rb
Rails.application.routes.draw do

  root to: 'site#index'
  get '/about' => 'static_pages#about', as: :about
  get '/contacts' => 'contacts#new', as: :contact
  resources 'contacts', only: [:new, :create]
  get '/web_resources' => 'static_pages#web_resources', as: :web_resources
  get '/faq' => 'static_pages#faq'
  get '/chart' => 'static_pages#chart'

  devise_for :users,
             singular: :user,
             controllers: { registrations: 'registrations',
                            omniauth_callbacks: 'apis' },
             path: '',
             path_names: { sign_in: 'login',
                           sign_out: 'logout',
                           sign_up: 'register',
                           edit: 'dashboard/profile/edit' }

  devise_scope :user do
    get '/apis/github/link' => 'apis#github_callback', as: :github_callback
  end
  resource :github_webhooks, only: :create,
                             defaults: { formats: :json }

  namespace :dashboard do
    get '/' => 'base#index'
    get '/webresources' => 'base#resources'
    get '/profile' => 'users#profile'
    get '/calendar' => 'events#index'
    get '/leaderboard' => 'base#leaderboard'

    resources :todos
    resources :events
    resources :assignments,
                            only: [:show, :index] do
      resources :answers, except: [:show]
    end
  end

  namespace :staff do
    get '/' => 'base#index'
    get '/base/admin'
    get '/profile' => 'members#profile'
    resources :locations
    resources :courses
    resources :members
    put '/accept_answer' => 'answers#update_answer_acceptance'
    resources :cohorts do
      get '/students/new' => 'users#new', as: :new_student
      resources :users, path: 'students'
      resources :assignments
      resources :repos
      resources :schedules
    end
  end

  resources :boards do
    resources :conversations do
      resources :comments
    end
  end
end

app/models/assignment.rb
# == Schema Information
#
# Table name: assignments
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  category    :string(255)
#  cohort_id   :integer
#  description :text
#  due_date    :date
#  created_at  :datetime
#  updated_at  :datetime
#

class Assignment < ActiveRecord::Base
  belongs_to :cohort
  has_many :pull_requests
  has_many :answers, dependent: :destroy
  validates :name, :description, presence: :true

  def accepted_answers
    answers.where(accepted: true)
  end

  def percent_answers_accepted
    # should probably change to accepted answers / total answers
    100.0 * (accepted_answers.count.to_f / cohort.users.student.count)
  end

  def percent_answered
    100.0 * (answers.count.to_f / cohort.users.student.count)
  end
end

app/controllers/dashboard/assignments_controller.rb
class Dashboard::AssignmentsController < ApplicationController
  include SetCohort
  before_action :authenticate_user!
  before_action :set_cohort

  def index
    @assignments = @cohort.assignments.order(:due_date)
  end

  def show
    @assignment = @cohort.assignments.includes(:answers).includes(:pull_requests).find(params[:id])
  end

  private

  # def set_cohort
  #   @cohort = current_user.cohort
  # end

  # def set_assignment
  #   @assignment = @cohort.assignments.find(params[:id])
  # end

  def assignment_params
    params.require(:assignment).permit(:name,
                                       :description,
                                       :category,
                                       :due_date,
                                       :cohort_id)
  end
end

app/controllers/staff/answers_controller.rb
class Staff::AnswersController < ApplicationController
  before_action :authenticate_user!

  def update_answer_acceptance
    @answer = Answer.find(params[:answer_id])
    checked = params[:accepted] || false
    @answer.update_attribute(:accepted, checked)
    @anwser.user.add_points(25, category: 'Assignments')
    respond_to do |format|
      format.all { render nothing: true, status: 200 }
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:title,
                                   :body,
                                   :accepted,
                                   :assignment_id,
                                   :user_id,
                                   :answer_id)
  end
end

app/controllers/staff/assignments_controller.rb
class Staff::AssignmentsController < ApplicationController
  include SetCohort
  before_action :authenticate_user!
  before_action :ensure_staff
  before_action :set_cohort
  before_action :set_assignment, only: [:edit, :update, :destroy]

  def index
    @assignments = @cohort.assignments.order(:due_date)
  end

  def show
    @assignment = @cohort.assignments.includes(:answers).includes(:pull_requests).find(params[:id])
  end

  def edit
  end

  def update
    if @assignment.update(assignment_params)
      redirect_to staff_cohort_assignments_url,
                  notice: 'Assignment was successfully updated.'
    else
      render :edit
    end
  end

  def new
    @assignment = Assignment.new
  end

  def create
    @assignment = @cohort.assignments.build(assignment_params)

    if @assignment.save
      redirect_to staff_cohort_assignments_url,
                  notice: 'Assignment was successfully created.'
    else
      render :new
    end
  end

  def destroy
    begin
      @assignment.destroy
      flash[:notice] = 'Assignment deleted!'
    rescue StandardError => error
      flash[:notice] = error.message
    end
    redirect_to staff_cohort_assignments_url
  end

  private

  def set_assignment
    @assignment = @cohort.assignments.find(params[:id])
  end

  def assignment_params
    params.require(:assignment).permit(:name,
                                       :description,
                                       :category,
                                       :due_date,
                                       :cohort_id)
  end
end

app/controllers/staff/base_controller.rb
class Staff::BaseController < ApplicationController
  before_action :authenticate_user!

  def index
    @cohorts = Cohort.all
    @cohort = Cohort.new
  end

  def admin
    @location = Location.new
    @course = Course.new
    @member = User.new(role: :staff)
    @locations = Location.all
    @courses = Course.all
    @members = User.staff.all
  end
end

app/controllers/staff/cohorts_controller.rb
class Staff::CohortsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_cohort, only: [:show, :edit, :update, :destroy]

  def index
    @cohorts = Cohort.all
  end

  def show
  end

  def new
    @cohort = Cohort.new
  end

  def edit
  end

  def update
    if @cohort.update_attributes(cohort_params)
      redirect_to staff_cohort_path, notice: 'Cohort updated!'
    else
      alert_and_render('Could not update', :edit)
    end
  end

  def create
    @cohort = Cohort.new(cohort_params)
    if @cohort.save
      redirect_to staff_cohort_path(@cohort), notice: 'New cohort added'
    else
      alert_and_render('Could not save cohort', :new)
    end
  end

  def destroy
    @cohort.destroy
    redirect_to staff_cohorts_path, notice: 'Cohort Removed'
  end

  private

  def cohort_params
    params.require(:cohort).permit(:starts_at,
                                   :ends_at,
                                   :name,
                                   :location_id,
                                   :course_id)
  end

  def set_cohort
    @cohort = Cohort.find(params[:id])
  end
end

app/controllers/staff/courses_controller.rb
class Staff::CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  def index
    @courses = Course.all
  end

  def show
  end

  def edit
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to staff_base_admin_path, notice: 'Course has been added!'
    else
      alert_and_render('Could not save course info', :new)
    end
  end

  def update
    if @course.update_attributes(course_params)
      redirect_to staff_base_admin_path, notice: 'All up to date'
    else
      alert_and_render('There was an issue updating', :edit)
    end
  end

  def destroy
    @course.destroy
    redirect_to staff_base_admin_path, notice: 'Course has been deleted'
  end

  private

  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:name,
                                 :description,
                                 :duration,
                                 :duration_unit,
                                 :price)
  end
end

app/controllers/staff/locations_controller.rb
class Staff::LocationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  def index
    @locations = Location.all
  end

  def show
  end

  def new
    @location = Location.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @location = Location.new(location_params)
    if @location.save
      redirect_to staff_base_admin_path, notice: 'Welcome to the family!'
    else
      alert_and_render('Could not save location info', :new)
    end
  end

  def edit
  end

  def update
    if @location.update_attributes(location_params)
      redirect_to staff_path, notice: 'All up to date'
    else
      alert_and_render('There was an issue updating', :edit)
    end
  end

  def destroy
    @location.destroy
    redirect_to staff_base_admin_path, notice: 'Sad to see you go'
  end

  private

  def set_location
    @location = Location.find(params[:id])
  end

  def location_params
    params.require(:location).permit(:name, :time_zone_name)
  end
end

app/controllers/staff/members_controller.rb
class Staff::MembersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  def index
    @members = User.staff.all
  end

  def show
   # @member = redirect_to staff_member_path(params[:id])
   # @member = User.find(params[:id])
  end

  def profile
    @member = current_user
  end

  def new
    @member = User.new(role: :staff)
  end

  def create
    @member = User.build_with_temp_password(member_params)
    @member.staff!
    if @member.save
      StudentMailer.welcome_email(@member).deliver
      redirect_to staff_base_admin_path, notice: 'Welcome to the family!'
    else
      alert_and_render('Could not save admin info', :new)
    end
  end

  def edit
  end

  def update
    if @member.update_attributes(member_params)
      redirect_to staff_member_path(@member), notice: 'All up to date'
    else
      alert_and_render('There was an issue updating', :edit)
    end
  end

  def destroy
    @member.destroy
    redirect_to staff_base_admin_path, notice: 'Sad to see you go'
  end

  private

  def set_member
    @member = User.find(params[:id])
  end

  def member_params
    params.require(:user).permit(:first_name, :last_name, :email, :role)
  end
end

app/controllers/staff/repos_controller.rb
class Staff::ReposController < ApplicationController
  include SetCohort
  before_action :authenticate_user!
  before_action :ensure_staff
  before_action :set_cohort
  before_action :set_repo, only: [:show, :edit, :update, :destroy]

  def index
    @repos = @cohort.repos.all
  end

  def show
  end

  def edit
  end

  def update
    if @repo.update(repo_params)
      redirect_to staff_cohort_repos_url,
                  notice: 'Repo was successfully updated.'
    else
      render :edit
    end
  end

  def new
    @repo = Repo.new
  end

  def create
    @repo = @cohort.repos.build(repo_params)

    if @repo.save
      redirect_to staff_cohort_repos_url,
                  notice: 'Repo was successfully created.'
    else
      render :new
    end
  end

  def destroy
    begin
      @repo.destroy
      flash[:notice] = 'Repo deleted!'
    rescue StandardError => error
      flash[:notice] = error.message
    end
    redirect_to staff_cohort_repos_url
  end

  private

  def set_repo
    @repo = @cohort.repos.find(params[:id])
  end

  def repo_params
    params.require(:repo).permit(:name,
                                 :link,
                                 :cohort_id)
  end
end

app/controllers/staff/schedules_controller.rb
class Staff::SchedulesController < ApplicationController
  include SetCohort
  before_action :authenticate_user!
  before_action :ensure_staff
  before_action :set_cohort
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  def index
    @schedules = @cohort.schedules.all
  end

  def show
  end

  def edit
  end

  def update
    if @schedule.update_attributes(schedule_params)
      redirect_to staff_cohort_schedules_path(@cohort),
                  notice: 'Schedule was successfully updated.'
    else
      render :edit
    end
  end

  def new
    @schedule = @cohort.schedules.new
  end

  def create
    @schedule = @cohort.schedules.new(schedule_params)

    if @schedule.save
      redirect_to staff_cohort_schedules_path(@cohort),
                  notice: 'Schedule was successfully created.'
    else
      render :new
    end
  end

  def destroy
      @schedule.destroy
      redirect_to staff_cohort_schedules_path
  end

  private

  def set_schedule
    @schedule = @cohort.schedules.find(params[:id])
  end

  def schedule_params
    params.require(:schedule).permit(:day, :description, :cohort_id)
  end
end

app/controllers/staff/users_controller.rb
class Staff::UsersController < ApplicationController
  include SetCohort
  before_action :authenticate_user!
  before_action :ensure_staff, only: [:new, :create]
  before_action :set_cohort
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  def edit
  end

  def new
    @student = @cohort.users.build_with_temp_password
  end

  def create
    @student = @cohort.users.build_with_temp_password(user_params)

    if @student.save
      StudentMailer.welcome_email(@student).deliver
      redirect_to staff_cohort_path(@cohort), notice: 'Student created!'
    else
      alert_and_render('Could not add new student', :new)
    end
  end

  def update
    if @student.update_info(user_params)
      redirect_to staff_cohort_path(@cohort), notice: 'Student updated!'
    else
      alert_and_render('Could not update student', :edit)
    end
  end

  def destroy
    @student.destroy
    redirect_to staff_cohort_path(@cohort), notice: 'Student was deleted'
  end

  def profile
    @user = current_user
  end

  def show
  end

  private

  def set_student
    @student = @cohort.users.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :email,
                                 :password,
                                 :password_confirmation,
                                 :hometown,
                                 :github_username,
                                 :github_email)
  end
end

app/helpers/dashboard/assignments_helper.rb
module Dashboard::AssignmentsHelper
end

app/helpers/staff/admin_helper.rb
module Staff::AdminHelper
end

app/helpers/staff/answers_helper.rb
module Staff::AnswersHelper
end

app/helpers/staff/assignments_helper.rb
module Staff::AssignmentsHelper
end

app/helpers/staff/base_helper.rb
module Staff::BaseHelper
end

app/helpers/staff/cohorts_helper.rb
module Staff::CohortsHelper
end

app/helpers/staff/courses_helper.rb
module Staff::CoursesHelper
end

app/helpers/staff/locations_helper.rb
module Staff::LocationsHelper
end

app/views/staff/assignments/_assignments_modal.html.erb
<div class="modal fade" id="Assignments" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Add a New Assignment</h4>
      </div>
      <div class="modal-body">
        <%= render 'staff/assignments/form' %>
      </div>
     <!--  <div class="modal-footer">
        <button type="button" class="btn btn-primary pull-right">Save changes</button>
      </div> -->
    </div>
  </div>
</div>

app/views/staff/assignments/_form.html.erb
<%= form_for([:staff, @cohort, @assignment]) do |f| %>
<% if @assignment.errors.any? %>
    <div id='error_explanation'>
      <h2><%= pluralize(@assignment.errors.count, "error") %> prohibited
          this assignment from being saved:</h2>
      <ul>
        <% @assignment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Begin rendering the form -->
  <div class= 'form-group'>
    <%= f.label :name, 'Assignment Title:' %><br>
    <%= f.text_field :name, placeholder: 'Assignment Title', class: 'form-control input-lg' %>
  </div>
  <div class= 'form-group'>
    <%= f.label :description, 'Description:' %><br>
    <%= f.text_area :description, placeholder: 'Description', class: 'form-control input-lg' %>
  </div>  
  <div class= 'form-group'>
    <%= f.label :category, 'Category:' %><br>
    <%= f.select :category, [['Ruby', 'ruby'],
                             ['Rails', 'rails'],
                             ['JavaScript', 'javascript']],
                            class: 'form-control input-lg' %>
  </div>
  <div class= 'form-group'>
    <%= f.label :due_date, 'Due Date:' %><br>
    <%= f.date_select :due_date, order: [:month, :day, :year],
                                 start_year: Date.today.year %>
  </div>

  <%= f.submit 'Submit', class: 'btn btn-primary' %> 
  
  <%= link_to 'Back', staff_cohort_assignments_path, class: 'btn btn-primary' %><br><br>
<% end %>

app/views/staff/assignments/edit.html.erb
<%- page_header 'Edit Assignment' %>
<!-- <h1>Edit Assignment</h1> -->
<%= render 'form' %>

app/views/staff/assignments/index.html.erb
<%- page_header 'Assignments Listing' %>
<!-- <h1>Assignments Listing</h1> -->
<p>This cohort doesn't have nearly enough work to do! You should add more assignments!</p>

<table class='table table-hover'>
  <thead>
    <tr>
      <th>Assignment</th>
      <th>Category</th>
      <th>Due Date</th>
      <th>Answered</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assignments.each do |assignment| %>
      <tr>
        <td><%= assignment.name %></td>
        <td><%= assignment.category %></td>
        <td><%= assignment.due_date.to_s(:long_ordinal) %></td>
        <td>
          <div class="progress">
            <div class="progress-bar progress-bar-striped active" 
                 role="progressbar"
                 aria-valuenow="<%= assignment.percent_answered %>"
                 aria-valuemin="0"
                 aria-valuemax="100"
                 style="width: <%= assignment.percent_answered %>%;">
              <span><%= number_to_percentage(assignment.percent_answered,
                                             precision: 0) %></span>
            </div>
          </div>
        </td>
        <td><%= link_to 'View', [:staff, @cohort, assignment],
                                class: 'btn btn-xs btn-default' %></td>
        <td><%= link_to 'Edit', edit_staff_cohort_assignment_path(@cohort, assignment),
                                class: 'btn btn-xs btn-default' %></td>
        <td><%= link_to 'Delete', [:staff, @cohort, assignment],
                                  class: 'btn btn-xs btn-default', method: :delete, 
                                        data: { 
                                                confirm: 'Are you sure you want to '\
                                                         'delete this assignment?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Add Assignment', new_staff_cohort_assignment_path(@cohort), method: 'get', remote: true,
                              class: 'btn btn-primary' %> 
<div id='modalDiv'></div>

app/views/staff/assignments/new.html.erb
<%- page_header 'Add New Assignment' %>
<!-- <h2>Add New Assignment</h2> -->
<%= render 'form' %>

app/views/staff/assignments/new.js.erb
$('#modalDiv').html('<%= j render "assignments_modal" %>').find('.modal').modal();

app/views/staff/assignments/show.html.erb
<%- page_header "[ID: #{@assignment.id}] #{@assignment.name}" %>
<% content_for :title, @assignment.name %>
<h2><%= "[ID: #{@assignment.id}] #{@assignment.name}" %></h2>
<h5>
Category: <%= @assignment.category %> | 
Due: <%= @assignment.due_date.to_s(:long_ordinal) %>
</h5>
<br>
<h4>Assignment Description:</h4>
<p><%= @assignment.description %></p>
<%= link_to 'Edit Assignment', edit_staff_cohort_assignment_path(@cohort, @assignment), 
                               class: 'btn btn-sm btn-primary' %>
<%= link_to 'Back', staff_cohort_assignments_path, class: 'btn btn-sm btn-primary'%><br>

<%= render 'shared/answers' %>